version: '3.8'

services:
  springapp:
    build:
      context: .
    container_name: spring-app
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - redis
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/apirate
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
